### ISSUE TITLE
Flipped result on recording with Unity 2017.3 Movie API

### ISSUE THREAD

**Issue by atrblizzard** [Unity-Technologies/GenericFrameRecorder#37]
**What happened?**
The recorded movie using the Movie API from Unity 2017.3 is being flipped horizontally. Settings used are Frame Buffer, Game Display as Source and Capture UI enabled.

**Is it reproduceable?**
Yes

**Released package version / tag?**
v0.2 (0.2.170919-05)

**Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?**
2017.3, Windows 10, Standalone Windows

**Comment by Jamoke** [comment]
I've seen this issue in 2017.2.0f3 as well.   Added the framework to my project, and the output is Upside Down.  (Version: 0.1 (Sep 15, 2017))

**Comment by jasonm-unity** [comment]
fixed in next release 0.2.0016 and up.

**Comment by pfarnach** [comment]
@jasonm-unity I'm still seeing this issue with 2017.3.0f3 on macOS High Sierra, Recorder v0.2.0027.  Should I create a new issue?  It seems like the issue is also referenced in https://github.com/Unity-Technologies/GenericFrameRecorder/issues/27.  I believe the recorder was working fine when I last used it in 2017.2.

**Comment by jasonm-unity** [comment]
@Jamoke I've had an other report also stating that the output is flipped and it may have been related to how the 0.2.28 package was generated. just to confirm, if you open up the menu tools/recorder/about , what version is being shown?

**Comment by githubsoooh** [comment]
I have also this issue.

Unity 2017.3.0f3, macOS High Sierra, Recorder 0.2.0031
